name: minestrix
description: A privacy focused social media based on matrix

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.6.5+13

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Matrix
  matrix:
    git:
      url: https://github.com/MinesTRIX/matrix-dart-sdk.git
      ref: henri2h/index-events-by-event-type

  flutter_olm:
    path: ../../olm/flutter
  flutter_openssl_crypto:
    path: ../../flutter_openssl_crypto

  # Database
  hive_flutter: ^1.1.0

  provider: ^6.0.1

  # navigator
  auto_route: ^7.4.0

  # web navigator for SSO
  webview_flutter: ^4.0.1
  url_launcher: ^6.0.3

  flutter_typeahead: ^4.0.0

  # Post formating
  flutter_markdown:
  emoji_picker_flutter: ^1.2.1

  # images
  image_picker:
  file_picker: ^5.2.5
  path_provider: ^2.0.5
  native_imaging:
    path: ../../native_imaging

  # time formating
  timeago: ^3.0.2

  # storage
  encrypt: ^5.0.1

  localstorage: ^4.0.0+1
  flutter_secure_storage: ^9.0.0

  # cache
  flutter_cache_manager: ^3.0.1
  cached_network_image: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.1

  # Notifications
  flutter_local_notifications: ^16.1.0
  unifiedpush: ^5.0.0
  desktop_notifications: ^0.6.3

  # Flushbar
  another_flushbar: ^1.10.25

  #dialogs
  adaptive_dialog: ^1.9.0-0

  package_info_plus: ^4.1.0

  minestrix_chat:
    path: ../lib
  
  infinite_list:
    git:
      url: https://gitlab.com/minestrix/infinite-list.git
      ref: henri2h/enhancements

  collection: ^1.15.0-nullsafety.4
  connectivity_plus: ^4.0.1
  just_audio: ^0.9.20
  flutter_ringtone_player: ^3.2.0
  desktop_lifecycle: ^0.1.0
  callkeep: ^0.3.2
  flutter_webrtc: ^0.9.2
  desktop_webview_window: ^0.2.0
  settings_ui: ^2.0.2
  flutter_datetime_picker: ^1.5.1
  intl: ^0.18.0
  scroll_to_index: ^3.0.1
  video_player: ^2.5.3
  camera: ^0.10.5+2
  dynamic_color: ^1.6.6
  media_kit: ^1.1.7
  video_compress: ^3.1.2

# Override due to https://github.com/mogol/flutter_secure_storage/issues/616
dependency_overrides:
  flutter_secure_storage_linux:
    git:
      url: https://github.com/tomekit/flutter_secure_storage.git
      ref: develop
      path: flutter_secure_storage_linux

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.0
  auto_route_generator: ^7.1.1
  build_runner: ^2.1.2
  import_sorter: ^4.6.0
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/verification.png
    - assets/sas-emoji.json
    - assets/icon_512.png
    - assets/bg_paris.jpg

  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto/Roboto-Regular.ttf
        - asset: fonts/Roboto/Roboto-Italic.ttf
          style: italic
        - asset: fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: NotoEmoji
      fonts:
        - asset: fonts/NotoEmoji/NotoColorEmoji.ttf

